name: Update Google Sheet Daily

on:
  schedule:
    - cron: "0 2 * * *"  # Runs every day at 2 AM UTC (7:30 AM IST)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas sqlalchemy psycopg2-binary gspread google-auth

      - name: Run script to update Google Sheet
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        run: |
          python main.py  # Replace with your script name if different
